player.setav Acrobatics 0
player.setav Alchemy 0
player.setav Alteration 0
player.setav Armorer 0
player.setav Athletics 0
player.setav Blade 0
player.setav Block 0
player.setav Blunt 0
player.setav Conjuration 0
player.setav Destruction 0
player.setav HandToHand 0
player.setav HeavyArmor 0
player.setav Illusion 0
player.setav LightArmor 0
player.setav Marksman 0
player.setav Mercantile 0
player.setav Mysticism 0
player.setav Restoration 0
player.setav Security 0
player.setav Sneak 0
player.setav Speechcraft 0
