#!/bin/sh
set -eux

# No args.
# Not directly used.

# An array of all iterami repos.
iterami_repos='
9YG0E6r.htm
Aquarium-2D.htm
AudioEditor.htm
BaseConverter.htm
BinaryDataEndecoder.htm
BlindMouse.htm
Click.htm
Clock.htm
ColorDrops.htm
ColorSelector.htm
ColorSquares.htm
ColorSteps.htm
ColorWaves.htm
common
Countdown.htm
D2LoD-ArcaneSanctuary.htm
Docs.htm
DotEyeIllusion.htm
Dropdown.htm
Duel.htm
ESP-Test.htm
Finances.htm
Fireworks-2D.htm
FractalRunner-2D3D.htm
GradientIllusion.htm
Guess.htm
Guides.htm
Hallway-2D3D.htm
Hexagons-2D.htm
Hrad.htm
iterami.github.io
Jetpack-2D.htm
LayeredSnake-2D3D.htm
LocalStorage.htm
Match.htm
Math.htm
MediaDevicesTest.htm
Multiverse.htm
MultiverseEditor.htm
MultiverseViewer.htm
Notes.htm
Particleball-2D.htm
ParticleRun-2D.htm
PasswordGenerator.htm
PixelEditor.htm
PlusPlus.htm
Poem.htm
Profiler.htm
QjnyYap.htm
Rain-2D.htm
random_number_test.htm
RandomRepo.htm
ReactionTest.htm
RNG.htm
RockPaperScissors.htm
RomanNumerals.htm
RTS-Boxing.htm
Scripts
Slots.htm
Snakish.htm
SnowyMountains.htm
SolarSystem-2D.htm
SpeedButton.htm
SpeedShape.htm
SpeedText.htm
SpeedType.htm
Starfield-2D3D.htm
Sudoku.htm
TextEditor.gtk
TextInfo.htm
Time.htm
TimeColors.htm
Timer.htm
Trains-2D.htm
Tubes-2D3D.htm
U1.htm
UnitConverter.htm
URI.htm
Warped.htm
WASD-2D.htm
WindowInfo.htm
'
