#!/bin/sh

# No arguments.
# Not directly used.

# An array of all iterami repositories.
iterami_repositories='
9YG0E6r.htm
Alarm.htm
Aquarium-2D.htm
AspectRatio.htm
AudioEditor.htm
Avoidance-2D.htm
BaseConverter.htm
BinaryDataEndecoder.htm
Birthday.htm
Bookmarklets.htm
Calculator.htm
Chromium-iterami-DevTools
Chromium-iterami-Extension
Chromium-iterami-Theme
clearundostack
Click.htm
Clock.htm
ColorDrops.htm
ColorSelector.htm
ColorSquares.htm
ColorSteps.htm
ColorWaves.htm
common
ConfigFiles
Countdown.htm
D2LoD-ArcaneSanctuary.htm
Docs.htm
DotEyeIllusion.htm
Dropdown.htm
Duel.htm
EmojiText.htm
ESP-Test.htm
EVE-Overviews.yaml
EVETools.gtk
ExperienceCalculator.htm
FileBrowser.gtk
Fireworks-2D.htm
FractalRunner-2D3D.htm
GitHub-API.htm
GMod-iterami-Addon
Guess.htm
Guides.htm
Hallway-2D3D.htm
Hexagons-2D.htm
Hrad.htm
InterestCalculator.htm
IssueExport.htm
iterami.github.io
Jetpack-2D.htm
LayeredSnake-2D3D.htm
LocalStorage.htm
Match.htm
MC-iterami-DataPacks
MediaDevicesTest.htm
Multiverse.htm
MultiverseEditor.gtk
MultiverseEditor.htm
MultiverseLevels.htm
Notes.htm
OS.asm
Particleball-2D.htm
ParticleRun-2D.htm
PasswordGenerator.htm
Percentages.htm
PixelEditor.htm
Platform-2D.htm
Platform-2D.sh
PlusPlus.htm
Poem.htm
ProcessEditor
Profiler.htm
QjnyYap.htm
RNG.htm
Race-2D.htm
Rain-2D.htm
random_number_test.gtk
random_number_test.htm
RandomRepository.htm
RandomSCP.htm
ReactionTest.htm
RockPaperScissors.htm
RomanNumerals.htm
RPG-Above.htm
RPG-Side.htm
RTS-2D.htm
RTS-Boxing.htm
SC-AI.cpp
Scripts
Shooter-2D.htm
Slots.htm
Snakish.htm
SnowyMountains.htm
SolarSystem-2D.htm
SpeedButton.htm
SpeedShape.htm
SpeedText.htm
SpeedType.htm
Starfield-2D3D.htm
Sudoku.htm
Terminal.gtk
TextEditor.gtk
TextInfo.htm
Time.htm
TimeColors.htm
Timer.htm
TinyMCE-Editor.htm
Trains-2D.htm
Trigonometry.htm
Tubes-2D3D.htm
U1.htm
UnitConverter.htm
URI.htm
Warped.htm
WASD-2D.htm
WebBrowser.gtk
WindowInfo.htm
WZ2100-AI.js
'
