SetPrivateProfileString('Fonts','Zoom','114')
SetPrivateProfileString('Fonts','ja_JP','MEIRYO')
SetPrivateProfileString('Fonts','ko_KR','NANUM')
SetPrivateProfileString('Fonts','ru_RU','PTSERIF')
SetPrivateProfileString('Fonts','uk_UA','PERMIAN')
SetPrivateProfileString('Fonts','zh_CN','SIMSUN')
SetPrivateProfileString('Game Options','3E Thief Sneak Attack','0')
SetPrivateProfileString('Game Options','All Learn Spell Info','1')
SetPrivateProfileString('Game Options','Always Dither','1')
SetPrivateProfileString('Game Options','Always Run','1')
SetPrivateProfileString('Game Options','Area Effects Density','100')
SetPrivateProfileString('Game Options','Attack Sounds','1')
SetPrivateProfileString('Game Options','Auto Pause Center','1')
SetPrivateProfileString('Game Options','Auto Pause State','1727')
SetPrivateProfileString('Game Options','Bored Timeout','3000')
SetPrivateProfileString('Game Options','Classic Selection Circles','0')
SetPrivateProfileString('Game Options','Cleric Ranger Spells','1')
SetPrivateProfileString('Game Options','Color Circles','0')
SetPrivateProfileString('Game Options','Combat UI','0')
SetPrivateProfileString('Game Options','Command Sounds Frequency','2')
SetPrivateProfileString('Game Options','Confirm Dialog','0')
SetPrivateProfileString('Game Options','Critical Hit Screen Shake','0')
SetPrivateProfileString('Game Options','Difficulty Level','1')
SetPrivateProfileString('Game Options','Duplicate Floating Text','1')
SetPrivateProfileString('Game Options','Effect Text Level','63')
SetPrivateProfileString('Game Options','Environmental Audio','1')
SetPrivateProfileString('Game Options','Extra Feedback','0')
SetPrivateProfileString('Game Options','Filter Games','1')
SetPrivateProfileString('Game Options','Footsteps','1')
SetPrivateProfileString('Game Options','GUI Feedback Level','5')
SetPrivateProfileString('Game Options','HP Over Head','0')
SetPrivateProfileString('Game Options','Heal Party on Rest','1')
SetPrivateProfileString('Game Options','Health Bar Settings','15')
SetPrivateProfileString('Game Options','Hotkeys On Tooltips','1')
SetPrivateProfileString('Game Options','Infravision','0')
SetPrivateProfileString('Game Options','Journal Popups','1')
SetPrivateProfileString('Game Options','Keyboard Scroll Speed','50')
SetPrivateProfileString('Game Options','Locator Feedback Level','3')
SetPrivateProfileString('Game Options','Maximum HP','1')
SetPrivateProfileString('Game Options','Memory Level','1')
SetPrivateProfileString('Game Options','Message Box Top','175')
SetPrivateProfileString('Game Options','Mouse Scroll Speed','0')
SetPrivateProfileString('Game Options','Nightmare Bonus Gold','0')
SetPrivateProfileString('Game Options','Nightmare Bonus XP','0')
SetPrivateProfileString('Game Options','No Difficulty Based XP Bonus','1')
SetPrivateProfileString('Game Options','Over Confirm Everything','1')
SetPrivateProfileString('Game Options','Pausing Map','0')
SetPrivateProfileString('Game Options','Quick Item Mapping','1')
SetPrivateProfileString('Game Options','Ranged Weapon Switching','0')
SetPrivateProfileString('Game Options','Render Actions','0')
SetPrivateProfileString('Game Options','Render Explored Map','0')
SetPrivateProfileString('Game Options','Render Travel Regions','0')
SetPrivateProfileString('Game Options','Selection Sounds Frequency','3')
SetPrivateProfileString('Game Options','Show Actionbar Help','0')
SetPrivateProfileString('Game Options','Show Character HP','1')
SetPrivateProfileString('Game Options','Show Enemy Health Status','1')
SetPrivateProfileString('Game Options','Show Learnable Spells','1')
SetPrivateProfileString('Game Options','Show Message Box Hint','0')
SetPrivateProfileString('Game Options','Smooth Area Transitions','1')
SetPrivateProfileString('Game Options','Subtitles','1')
SetPrivateProfileString('Game Options','Suppress Extra Difficulty Damage','0')
SetPrivateProfileString('Game Options','Terrain Hugging','0')
SetPrivateProfileString('Game Options','Tiles Precache Percent','100')
SetPrivateProfileString('Game Options','Tutorial State','1')
SetPrivateProfileString('Game Options','Weather','1')
SetPrivateProfileString('Graphics','Backend','0')
SetPrivateProfileString('Graphics','Gameworld Scaling','1')
SetPrivateProfileString('Graphics','Gamma','100')
SetPrivateProfileString('Graphics','Greyscale On Pause','0')
SetPrivateProfileString('Graphics','Hardware Mouse Cursor','1')
SetPrivateProfileString('Graphics','Scale UI','1')
SetPrivateProfileString('Graphics','Show Black Space','0')
SetPrivateProfileString('Graphics','Use Character Highlights','1')
SetPrivateProfileString('Graphics','Use Double Size Cursors','1')
SetPrivateProfileString('Graphics','Use Linear Scaling','1')
SetPrivateProfileString('Graphics','Use Sprite Outlines','1')
SetPrivateProfileString('Graphics','Zoom Lock','0')
SetPrivateProfileString('Keymap Action','Attack','114')
SetPrivateProfileString('Keymap Action','Equipment','0')
SetPrivateProfileString('Keymap Action','Toggle Combat Log','0')
SetPrivateProfileString('Keymap Action','Toggle Quick Loot','0')
SetPrivateProfileString('Keymap Action','Stop','102')
SetPrivateProfileString('Keymap Character Selection','Multiselect 1-2','0')
SetPrivateProfileString('Keymap Character Selection','Multiselect 1-3','0')
SetPrivateProfileString('Keymap Character Selection','Multiselect 3-4','0')
SetPrivateProfileString('Keymap Character Selection','Multiselect 4-6','0')
SetPrivateProfileString('Keymap Character Selection','Multiselect 5-6','0')
SetPrivateProfileString('Keymap Character Selection','Multiselect all','50')
SetPrivateProfileString('Keymap Character Selection','Select Character 1','0')
SetPrivateProfileString('Keymap Character Selection','Select Character 2','0')
SetPrivateProfileString('Keymap Character Selection','Select Character 3','0')
SetPrivateProfileString('Keymap Character Selection','Select Character 4','0')
SetPrivateProfileString('Keymap Character Selection','Select Character 5','0')
SetPrivateProfileString('Keymap Character Selection','Select Character 6','0')
SetPrivateProfileString('Keymap Miscellaneous','Center Character','0')
SetPrivateProfileString('Keymap Miscellaneous','Quick Load','0')
SetPrivateProfileString('Keymap Miscellaneous','Quick Save','0')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Down','115')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Left','97')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Right','100')
SetPrivateProfileString('Keymap Miscellaneous','Scroll Up','119')
SetPrivateProfileString('Keymap Miscellaneous','Toggle Always Run','0')
SetPrivateProfileString('Keymap Page','Character Stats','99')
SetPrivateProfileString('Keymap Page','Inventory','98')
SetPrivateProfileString('Keymap Page','Journal','0')
SetPrivateProfileString('Keymap Page','Mage Spells','0')
SetPrivateProfileString('Keymap Page','Map','0')
SetPrivateProfileString('Keymap Page','Options','0')
SetPrivateProfileString('Keymap Page','Priest Spells','0')
SetPrivateProfileString('Keymap Page','Return To Game','0')
SetPrivateProfileString('Language','Text','en_US')
SetPrivateProfileString('Multiplayer','Disable Banters','1')
SetPrivateProfileString('Multiplayer','Enable Chat Menu','1')
SetPrivateProfileString('Program Options','3D Acceleration','1')
SetPrivateProfileString('Program Options','Brightness Correction','0')
SetPrivateProfileString('Program Options','Cloud Saves Enabled','1')
SetPrivateProfileString('Program Options','Disable Cosmetic Attacks','0')
SetPrivateProfileString('Program Options','Drop Capitals','1')
SetPrivateProfileString('Program Options','Font Name','')
SetPrivateProfileString('Program Options','Maximum Frame Rate','30')
SetPrivateProfileString('Program Options','Never Show Nuisance PST','1')
SetPrivateProfileString('Program Options','Path Search Nodes','32000')
SetPrivateProfileString('Program Options','Sprite Mirror','1')
SetPrivateProfileString('Program Options','Tooltips','0')
SetPrivateProfileString('Program Options','Translucent Shadows','1')
SetPrivateProfileString('Program Options','Use Touch Actionbar','0')
SetPrivateProfileString('Program Options','Volume Ambients','40')
SetPrivateProfileString('Program Options','Volume Movie','90')
SetPrivateProfileString('Program Options','Volume Music','41')
SetPrivateProfileString('Program Options','Volume SFX','80')
SetPrivateProfileString('Program Options','Volume Voices','100')
SetPrivateProfileString('Window','Full Screen','0')
SetPrivateProfileString('Window','Maximized','1')
